services:
  # db:
  #   image: postgres:15-bookworm
  #   container_name: postgres15
  #   restart: unless-stopped
  #   volumes:
  #     - ${APPDATA}postgres:/config:rw
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #   ports:
  #     - 5432:5432

  # adminer:
  #   image: adminer
  #   container_name: adminer
  #   restart: unless-stopped
  #   ports:
  #     - 8080:8080

  bheft_generator:
    container_name: bheft_generator
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5200:5200

  playwright:
    image: mcr.microsoft.com/playwright:v1.45.1-focal
    restart: unless-stopped 
    ports:
      - "9222:9222"
    command: npx playwright run-server --port=9222

  # watchtower:
  #   image: containrrr/watchtower
  #   container_name: watchtower
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
